require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BuildingsController do

  # This should return the minimal set of attributes required to create a valid
  # Building. As you add validations to Building, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all buildings as @buildings" do
      building = Building.create! valid_attributes
      get :index
      assigns(:buildings).should eq([building])
    end
  end

  describe "GET show" do
    it "assigns the requested building as @building" do
      building = Building.create! valid_attributes
      get :show, :id => building.id
      assigns(:building).should eq(building)
    end
  end

  describe "GET new" do
    it "assigns a new building as @building" do
      get :new
      assigns(:building).should be_a_new(Building)
    end
  end

  describe "GET edit" do
    it "assigns the requested building as @building" do
      building = Building.create! valid_attributes
      get :edit, :id => building.id
      assigns(:building).should eq(building)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Building" do
        expect {
          post :create, :building => valid_attributes
        }.to change(Building, :count).by(1)
      end

      it "assigns a newly created building as @building" do
        post :create, :building => valid_attributes
        assigns(:building).should be_a(Building)
        assigns(:building).should be_persisted
      end

      it "redirects to the created building" do
        post :create, :building => valid_attributes
        response.should redirect_to(Building.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved building as @building" do
        # Trigger the behavior that occurs when invalid params are submitted
        Building.any_instance.stub(:save).and_return(false)
        post :create, :building => {}
        assigns(:building).should be_a_new(Building)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Building.any_instance.stub(:save).and_return(false)
        post :create, :building => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested building" do
        building = Building.create! valid_attributes
        # Assuming there are no other buildings in the database, this
        # specifies that the Building created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Building.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => building.id, :building => {'these' => 'params'}
      end

      it "assigns the requested building as @building" do
        building = Building.create! valid_attributes
        put :update, :id => building.id, :building => valid_attributes
        assigns(:building).should eq(building)
      end

      it "redirects to the building" do
        building = Building.create! valid_attributes
        put :update, :id => building.id, :building => valid_attributes
        response.should redirect_to(building)
      end
    end

    describe "with invalid params" do
      it "assigns the building as @building" do
        building = Building.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Building.any_instance.stub(:save).and_return(false)
        put :update, :id => building.id, :building => {}
        assigns(:building).should eq(building)
      end

      it "re-renders the 'edit' template" do
        building = Building.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Building.any_instance.stub(:save).and_return(false)
        put :update, :id => building.id, :building => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested building" do
      building = Building.create! valid_attributes
      expect {
        delete :destroy, :id => building.id
      }.to change(Building, :count).by(-1)
    end

    it "redirects to the buildings list" do
      building = Building.create! valid_attributes
      delete :destroy, :id => building.id
      response.should redirect_to(buildings_url)
    end
  end

end
